### ISSUE TITLE
passband request: Super SDSS

### ISSUE THREAD

**Issue by JamesMunday98** [phoebe-project/phoebe2-tables#5] opened 2021-12-04 11:09 UTC
Hello.

Would you please add the HiPERCAM Super SDSS passbands in ugriz to the tables? I tried myself by following the guidance found here http://phoebe-project.org/docs/latest/tutorials/passbands for a chosen index but the resultant passband was not readable by phoebe after installing all required requisites - the created passband appears in the list if I search for all passbands, e.g. like the Custom:mypb stated in the guide, but can not be used as an input to any dataset. The guide additionally doesn't mention the inclusion of phoenix atmospheres, so I'm guessing it is outdated and may need tweaking. 

I'm struggling to find it now, but I remember reading somewhere that you need to install the Wilson-Devinney code from 2004 for the script to work. I also tried the more recent 2016 code which has additional indexes for typical filters. Phoebe produces a max index error, but after going into the passbands.py script and increasing the maximum index with the corresponding atmcof.dat and atmcofplanck.dat files, it did not like the files (here I was trying to use indexes 56-60 of the 2016 table). Would you please tweak the code to include the newer WD files too? The 2016 version is on the same ftp directory as the 2004. I can try to reproduce errors if that is useful, but if the doc is simply outdated then it is probably not.

Back to the passbands I would like, they are found from lines 43 to 47 at
http://www.vikdhillon.staff.shef.ac.uk/ultracam/filters/filters.html

Or the throughputs to the detector for ugriz are:
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.u_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.g_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.r_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.i_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.z_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter

Would you please add them?

Many Thanks,
James

**Comment by kecnry** [comment] 2023-02-22 18:12
closing as a duplicate of https://github.com/phoebe-project/phoebe2/issues/566 (already closed).

**Closed as completed by kecnry** 2023-02-22 18:12 UTC
